# Generated by Django 6.0.2 on 2026-04-01 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auctions', '0001_initial'),
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreed_deadline', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_START', 'Aguardando Início'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='PENDING_START', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('citizen_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='accounts.citizenprofile')),
                ('mei_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='accounts.meiprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.servicerequest')),
                ('winning_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_orders', to='auctions.bid')),
            ],
        ),
    ]
