# Generated by Django 6.0.2 on 2026-06-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizenprofile',
            name='total_services_requested',
        ),
        migrations.RemoveField(
            model_name='meiprofile',
            name='total_services_completed',
        ),
    ]
