# Generated by Django 6.0.2 on 2026-06-22 18:59

import os
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'rafabmussi@gmail.com')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'admin123')
    
    if not User.objects.filter(email=email).exists():
        User.objects.create(
            email=email,
            password=make_password(password),
            full_name='Admin',
            user_type='ADMIN',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
    else:
        # If user exists but might not be admin or have right password, we can optionally update it.
        # But to be safe, we just update the password to ensure they can login.
        user = User.objects.get(email=email)
        user.password = make_password(password)
        user.is_staff = True
        user.is_superuser = True
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_citizenprofile_total_services_requested_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
