# Generated by Django 6.0.2 on 2026-04-06 23:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviço',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('EMERGENCIA', 'Emergência')], default='MEDIA', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_AUCTION', 'Em Leilão'), ('AWARDED', 'Adjudicado'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('auction_end_at', models.DateTimeField(blank=True, null=True)),
                ('desired_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='accounts.address')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='services.servicecategory')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='accounts.citizenprofile')),
            ],
            options={
                'verbose_name': 'Solicitação de Serviço',
                'verbose_name_plural': 'Solicitações de Serviço',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='service_requests/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'Mídia da Solicitação',
                'verbose_name_plural': 'Mídias das Solicitações',
                'ordering': ['order'],
            },
        ),
    ]
