# Generated by Django 6.0.2 on 2026-03-27 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proposed_deadline', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('WITHDRAWN', 'Retirado'), ('WINNER', 'Vencedor'), ('REJECTED', 'Rejeitado')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mei_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='accounts.meiprofile')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='MEICategorySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mei_subscriptions', to='services.servicecategory')),
                ('mei_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subscriptions', to='accounts.meiprofile')),
            ],
            options={
                'unique_together': {('mei_profile', 'category')},
            },
        ),
    ]
